spring:
  application:
    name: consumer



server:
  port: 8082

dubbo:
  scan:
    base-packages: com.prectise.controller
  application:
    name: consumer

  registry:
    address: zookeeper://127.0.0.1:2181


